name: API-Pulse-Scheduler

on:
  #schedule:
    # Run every minute
    #- cron: '* * * * *'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  execute-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./scheduler

      - name: Run scheduler
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        run: node scheduler.js
        working-directory: ./scheduler
